version: '3.3'

services:
  infohouse:
    build: ./
    command: ./ house
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    restart: always
    image: postgres:16-alpine
    environment:

      POSTGRES_DB: "test_db"
      POSTGRES_USER: "house"
      POSTGRES_PASSWORD: 1212
    ports:
      - "5436:5432"